### PR TITLE
Responsive design for tablet and desktop

### PR DESCRIPTION
**Pull request by RalucaRbc**

### CODE REVIEW

**Review by marianzburlea — APPROVED** [review]
💯

**Review by M00N89 — APPROVED** [review]

**Review by M00N89 — APPROVED** [review]

**Review by M00N89 — APPROVED** [review]
👍🏻

**Review by robertoalx — APPROVED** [review]
Lot's of files changed :D Great job 👍 👍 💯

**Review by Constantin-Matei — APPROVED** [review]
👍

**Review by BogdanNegura — APPROVED** [review]
👍

**Pull request merged**
