### PR TITLE
Dev mariateo

### PR DESCRIPTION
**Pull request by MariaTeo**

### CODE REVIEW

**Review by RalucaRbc — APPROVED** [review]

**Review by andreimaff — APPROVED** [review]
Nice job!

**Review by M00N89 — COMMENTED** [review]
well done

**Review by M00N89 — COMMENTED** [review]
good job

**Comment by MariaTeo** [comment]
> good job

Thank you 😊

**Comment by MariaTeo** [comment]
> Nice job!

Thanks 🤩

**Review by marianzburlea — APPROVED** [review]

**Review by BogdanNegura — APPROVED** [review]
💯

**Comment by marianzburlea** [comment]
image

**Pull request closed without merging**
