### PR TITLE
Dev mariateo experience

### PR DESCRIPTION
**Pull request by MariaTeo**
finished experience section

### CODE REVIEW

**Review by BogdanNegura — APPROVED** [review]
💯  Traiasca "img" :)

**Review by biggicode — APPROVED** [review]

**Review by Constantin-Matei — APPROVED** [review]
Nice clean code :)

**Review by ValentinaVanu — COMMENTED** [review]
Good Job!

**Review by RalucaRbc — APPROVED** [review]
Looks fine 💯 well done Maria 👍

**Pull request merged**
